language: node_js
node_js:
  - 16.13.0
branchs:
  only:
    - master
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store
  - pnpm config set registry https://registry.npmmirror.com
  - pnpm lint
  - pnpm lint:fix
  - pnpm lint:style
install:
  - pnpm install
scripts:
  - pnpm build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  # 在 GitHub 上生成的令牌，允许 Travis 推送代码到你的仓库。
  # 在仓库对应的 Travis 设置页面中配置，用于安全控制。
  github_token: $GIT_TOKEN
  keep_history: true
  on:
    branch: travis-pages
