name: Deploy

on:
  push

jobs:
  Cloudbase:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install
        run: yarn
      - name: build
        run: yarn add axios && yarn build:cdn
      - name: Deploy static to github pagese 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action@v1.1.1
        with:
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          envId: ${{ secrets.ENV_ID }}
          staticSrcPath: dist
      - name: echo url
        run: echo -e "\033[4mhttps://dgiotdashboard-8gb17b3673ff6cdd-1253666439.tcloudbaseapp.com\033[0m"
