name: ubuntu-latest
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.3.0
          run_install: false
      - run: pnpm config set registry https://registry.npmmirror.com
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm lint:fix
      - run: pnpm lint:style
      - run: pnpm build
      - uses: actions/upload-artifact@v2
        name: Upload Installer
        with:
          name: WeakAuras-Companion-PRCI-Installer
          path: dist_electron/*.exe
